### ISSUE TITLE
sysdig role is not on ansible galaxy

### ISSUE THREAD

**Issue by lhoss** [valentinogagliardi/sysdig#5]
I'ld prefer to use your role (as it has more traction, 'stars') but following alternative role is easier to get running thx to galaxy availability: https://galaxy.ansible.com/kbrebanov/sysdig/

**Comment by valentinogagliardi** [comment]
@lhoss Hi, thanks for the interest. I've just uploaded the role to Galaxy https://galaxy.ansible.com/valentinogagliardi/sysdig/
